### ISSUE TITLE
Nowhere on this git page has the exe, its useless without one

### ISSUE THREAD

**Issue by SpicyCupcakes** [Mrakovic-ORG/WannabeSelfish#1]

**Comment by 0x11DFE** [comment]
Hello alright after few reflexion yes it could be interesting to have executables on releases for beginners.
https://github.com/Mrakovic-ORG/WannabeSelfish/releases

**Comment by owersite** [comment]
SpicyCupcakes, You are not really smart my friend.

**Comment by SpicyCupcakes** [comment]
I'm smarter than your dumbass.  At least I don't post shit on GitHub that
cannot be used.

**Comment by owersite** [comment]
how can't it be used? lmfao dead arguments against me
